@startuml
!include ../uportskin.plantuml
title Uport Generic Request Flow
participant ClientApp
participant UportMobile
actor Owner

ClientApp -> UportMobile : Signed Request (JWT)
UportMobile -> Owner : Authorize Request?
Owner -> UportMobile: Allow/Disallow
UportMobile -> ClientApp: Response

@enduml
