@startuml
!include ../uportskin.plantuml
title Example Identity Verification Flow
participant Issuer
participant UportMobile
actor Owner

Issuer -> UportMobile : Selective Disclosure Request
UportMobile -> Owner : Authorize Request?
Owner -> UportMobile: Allow/Disallow
UportMobile -> UportMobile: Sign Selective Disclosure Response
UportMobile -> Issuer: Selective Disclosure Response
Issuer <- Owner : Show passport
Issuer -> UportMobile : Verification
UportMobile -> Owner : Show Verification
UportMobile -> Issuer : Acknowledgement

@enduml
