@startuml
!include ../uportskin.plantuml
title Uport Ethereum Transaction Flow
participant ClientApp
participant UportMobile
actor Owner
participant FuelingService
database Ethereum

ClientApp -> UportMobile : ERC 76 Request
UportMobile -> Owner : Authorize Request?
Owner -> UportMobile: Allow/Disallow
UportMobile -> UportMobile: Sign Transaction
UportMobile -> FuelingService: Request gas for transaction
FuelingService -> Ethereum: Fueling Transaction
UportMobile -> Ethereum: Signed Transaction
UportMobile -> ClientApp: Transaction Hash
ClientApp <-> Ethereum: Transaction Confirmation

@enduml
