@startuml
!include ../uportskin.plantuml
title Uport Verified Claim Request Flow
participant ClientApp
participant UportMobile
actor Owner

ClientApp -> UportMobile : Verified Claim Request
UportMobile -> Owner : Authorize Request?
Owner -> UportMobile: Allow/Disallow
UportMobile -> UportMobile: Sign Verified Claim
UportMobile -> ClientApp: Send Verified Claim

@enduml
