@startuml
!include ../uportskin.plantuml
title Desktop Web Server App to Uport Mobile Request Flow
participant ClientBackEnd
participant ClientFrontEnd
participant UportMobile
actor Owner

ClientFrontEnd <- ClientBackEnd : Create Signed Request
ClientFrontEnd -> Owner : Show QR code containing request
Owner -> UportMobile: Scans QR code
UportMobile -> Owner : Authorize Request?
Owner -> UportMobile: Allow/Disallow
UportMobile -> ClientBackEnd: Send response
ClientBackEnd -> ClientFrontEnd: Handle response

@enduml
